sudo: required
# Above statement says we need superuser permission to always access this
language: generic

services:
  - docker
  # Automatically installs copy of docker into container
before_install:
  - docker build -t themarvelfan616/docker-react -f Dockerfile.dev .
  # Commands to run before installation
script:
  - docker run -e CI=true themarvelfan616/docker-react npm run test
#  - docker run themarvelfan616/docker-react npm run tests -- --coverage
  # Commands that actually run while testing
  # Travis CI either stops that test when exit code != 0, or the tests pass, and it assumes that the test exited. However, in case of npm commands
  # the test will never exit automatically.
  # Both ways work, but uncommented one is standard
  # coverage flag provides output about how much of the code is covered by the test, but Travis CI reads only the exit code and not the output
# below section deals with specifying deployment specification to Travis CI
deploy:
  provider: elasticbeanstalk
  # Pre configured
  region: "ap-southeast-2"
  # Above obtained from aws itself
  app: "frontend"
  env: "Frontend-env"
  # Above is obtained from aws itself
  bucket_name: "elasticbeanstalk-ap-southeast-2-381491946362"
  # Above is obtained from aws itself
  bucket_path: "frontend"
  # exact same as app name
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY